#!/usr/bin/env python
import os, sys

from rconfig import *

def main():
	if len(sys.argv) != 3 and len(sys.argv) != 4:
		print("Example: rscp cfg local remote\n")
		print("Example: rscp cfg remote\n")

	try:
		cfg = globals()[sys.argv[1]];
	except Exception, e:
		print('Invalid config: %s' % sys.argv[1])
		return

	port = getStringField(cfg, 'port_ssh', 22)
	user = getStringField(cfg, 'user', 'root')

	if len(sys.argv) == 3:
		os.execlp('scp', 'scp', '-P' + port, '%s@%s:%s' % (user, cfg['host'], sys.argv[2]), './');
	else:
		os.execlp('scp', 'scp', '-P' + port, sys.argv[2], '%s@%s:%s' % (user, cfg['host'], sys.argv[3]));

if __name__ == '__main__':
	main()
