#!/usr/bin/env python
import os, sys
from rcommon import *
from rconfig import *
from argparse import *

def main(argv):
	parser = ArgumentParser(description='Copy file between two host.', epilog='rtools '+getVersion())
	parser.add_argument('-g', dest='opr', action='store_false', help='get file. default')
	parser.add_argument('-p', dest='opr', action='store_true', help='put file.')
	parser.add_argument('cfg', metavar='cfg', type=str, help='the name of configuration.')
	parser.add_argument('src', type=str, help='source file.')
	parser.add_argument('dst', type=str, help='destion file.')
	args = parser.parse_args();

	try:
		cfg = globals()[args.cfg];
	except Exception, e:
		print('Invalid config: %s' % args.cfg)
		return

	port = getStringField(cfg, 'port_ssh', 22)
	user = getStringField(cfg, 'user', 'root')

	if not args.opr:
		# get
		os.execlp('scp', 'scp', '-P' + port, '%s@%s:%s' % (user, cfg['host'], args.src), args.dst);
	else:
		# put
		os.execlp('scp', 'scp', '-P' + port, args.src, '%s@%s:%s' % (user, cfg['host'], args.dst));

if __name__ == '__main__':
	main(sys.argv)
